# Generated by Django 2.1.5 on 2019-02-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_auto_20190211_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='driver_phone',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='owner_phone',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='sharer_phone',
        ),
        migrations.AlterField(
            model_name='ride',
            name='sharer_id',
            field=models.IntegerField(default=0),
        ),
    ]
