# Generated by Django 2.1.5 on 2019-02-13 23:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_auto_20190212_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='arrival_time_owner',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='ride',
            name='driver_email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ride',
            name='driver_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ride',
            name='driver_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ride',
            name='license_plate_number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ride',
            name='max_capacity',
            field=models.IntegerField(blank=True, default=4),
        ),
        migrations.AlterField(
            model_name='ride',
            name='special_requests_driver',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ride',
            name='vehicle_type_registered',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
