# Generated by Django 2.1.5 on 2019-02-12 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='phone',
            new_name='username',
        ),
    ]
