# Generated by Django 2.2 on 2019-04-17 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_frontend', '0002_auto_20190414_0347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='package_id',
        ),
    ]
