# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: webapp_amazon.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='webapp_amazon.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x13webapp_amazon.proto\"\x1f\n\x0brequest_buy\x12\x10\n\x08order_id\x18\x01 \x02(\x03\"\"\n\x0erequest_cancel\x12\x10\n\x08order_id\x18\x01 \x02(\x03\"i\n\x1frequest_change_delivery_address\x12\x10\n\x08order_id\x18\x01 \x02(\x03\x12\x19\n\x11new_destination_x\x18\x02 \x02(\x05\x12\x19\n\x11new_destination_y\x18\x03 \x02(\x05\"\x86\x01\n\nWACommands\x12\x19\n\x03\x62uy\x18\x01 \x01(\x0b\x32\x0c.request_buy\x12\x1f\n\x06\x63\x61ncel\x18\x02 \x01(\x0b\x32\x0f.request_cancel\x12<\n\x12\x63hange_destination\x18\x03 \x01(\x0b\x32 .request_change_delivery_address')
)




_REQUEST_BUY = _descriptor.Descriptor(
  name='request_buy',
  full_name='request_buy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='order_id', full_name='request_buy.order_id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=54,
)


_REQUEST_CANCEL = _descriptor.Descriptor(
  name='request_cancel',
  full_name='request_cancel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='order_id', full_name='request_cancel.order_id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=90,
)


_REQUEST_CHANGE_DELIVERY_ADDRESS = _descriptor.Descriptor(
  name='request_change_delivery_address',
  full_name='request_change_delivery_address',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='order_id', full_name='request_change_delivery_address.order_id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='new_destination_x', full_name='request_change_delivery_address.new_destination_x', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='new_destination_y', full_name='request_change_delivery_address.new_destination_y', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=197,
)


_WACOMMANDS = _descriptor.Descriptor(
  name='WACommands',
  full_name='WACommands',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='buy', full_name='WACommands.buy', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cancel', full_name='WACommands.cancel', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='change_destination', full_name='WACommands.change_destination', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=334,
)

_WACOMMANDS.fields_by_name['buy'].message_type = _REQUEST_BUY
_WACOMMANDS.fields_by_name['cancel'].message_type = _REQUEST_CANCEL
_WACOMMANDS.fields_by_name['change_destination'].message_type = _REQUEST_CHANGE_DELIVERY_ADDRESS
DESCRIPTOR.message_types_by_name['request_buy'] = _REQUEST_BUY
DESCRIPTOR.message_types_by_name['request_cancel'] = _REQUEST_CANCEL
DESCRIPTOR.message_types_by_name['request_change_delivery_address'] = _REQUEST_CHANGE_DELIVERY_ADDRESS
DESCRIPTOR.message_types_by_name['WACommands'] = _WACOMMANDS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

request_buy = _reflection.GeneratedProtocolMessageType('request_buy', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST_BUY,
  __module__ = 'webapp_amazon_pb2'
  # @@protoc_insertion_point(class_scope:request_buy)
  ))
_sym_db.RegisterMessage(request_buy)

request_cancel = _reflection.GeneratedProtocolMessageType('request_cancel', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST_CANCEL,
  __module__ = 'webapp_amazon_pb2'
  # @@protoc_insertion_point(class_scope:request_cancel)
  ))
_sym_db.RegisterMessage(request_cancel)

request_change_delivery_address = _reflection.GeneratedProtocolMessageType('request_change_delivery_address', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST_CHANGE_DELIVERY_ADDRESS,
  __module__ = 'webapp_amazon_pb2'
  # @@protoc_insertion_point(class_scope:request_change_delivery_address)
  ))
_sym_db.RegisterMessage(request_change_delivery_address)

WACommands = _reflection.GeneratedProtocolMessageType('WACommands', (_message.Message,), dict(
  DESCRIPTOR = _WACOMMANDS,
  __module__ = 'webapp_amazon_pb2'
  # @@protoc_insertion_point(class_scope:WACommands)
  ))
_sym_db.RegisterMessage(WACommands)


# @@protoc_insertion_point(module_scope)
